name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Pre-installed Terraform (if any)
        run: sudo rm -f $(which terraform) || true

      - name: Install Terraform 1.6.3
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3  # Ensure GitHub Actions installs 1.6.3

      - name: Verify Terraform version
        run: terraform --version  # Ensure the correct version is installed

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
